-- SCD Type 2 for web.jobs_resume: keep every saved version of a per-job
-- tailored résumé instead of overwriting. Previously Save was an upsert keyed
-- on (job_id, sys_profile) — a single row per key — so a re-save (or, as we
-- learned the hard way, a stray POST to /resume.pdf) destroyed the prior text.
--
-- New shape: each save inserts a new row with an incrementing `version`; the
-- prior current row is expired (is_current=false, valid_to=now()) but kept.
-- `generated_at` is the version's valid-from. A surrogate `id` becomes the PK
-- (multiple rows now share a (job_id, sys_profile) key) and a partial unique
-- index enforces exactly one current version per key.
--
-- Idempotent for the no-psql cmd/migrate re-run path (IF [NOT] EXISTS / DO).

ALTER TABLE web.jobs_resume
    ADD COLUMN IF NOT EXISTS version    integer     NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS is_current boolean     NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS valid_to   timestamptz,
    ADD COLUMN IF NOT EXISTS id         bigint GENERATED BY DEFAULT AS IDENTITY;

-- Swap the composite (job_id, sys_profile) PK for the surrogate id, so the
-- table can hold many versions per key. No FK references this table (006
-- deferred it), so the swap is safe.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'web.jobs_resume'::regclass AND contype = 'p'
          AND conname = 'resume_finalizations_pkey'
    ) THEN
        ALTER TABLE web.jobs_resume DROP CONSTRAINT resume_finalizations_pkey;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'web.jobs_resume'::regclass AND contype = 'p'
    ) THEN
        ALTER TABLE web.jobs_resume ADD PRIMARY KEY (id);
    END IF;
END $$;

-- Exactly one current version per (job_id, sys_profile).
CREATE UNIQUE INDEX IF NOT EXISTS jobs_resume_current_uk
    ON web.jobs_resume (job_id, sys_profile) WHERE is_current;
