-- Practice attempts: one row per uploaded run log, so the record of how you
-- did survives re-rolling the exercise. Deliberately NOT keyed to the current
-- challenge row — title and skills are denormalised so history stays readable
-- after the exercise is regenerated.
--
-- The natural key (job_id, sys_profile, started_at) is what the hub<->box merge
-- dedupes on: attempts are append-only personal records, same shape as
-- web.application_events, and never updated once written.
-- Idempotent for the cmd/migrate re-run path.

CREATE TABLE IF NOT EXISTS web.challenge_attempts (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            text        NOT NULL,
    sys_profile       text        NOT NULL,
    challenge_title   text        NOT NULL DEFAULT '',
    skills            text[]      NOT NULL DEFAULT '{}',
    started_at        timestamptz NOT NULL,
    finished_at       timestamptz,
    runs              int         NOT NULL DEFAULT 0,
    total_tests       int         NOT NULL DEFAULT 0,
    first_pass        int         NOT NULL DEFAULT 0,
    final_pass        int         NOT NULL DEFAULT 0,
    solved            boolean     NOT NULL DEFAULT false,
    -- 1-based run index at which every planted-bug test / every other test
    -- first went green. 0 means "never". bug_first is NULL when the exercise
    -- predates bug-test tracking or both went green on the same run.
    bug_green_run     int         NOT NULL DEFAULT 0,
    other_green_run   int         NOT NULL DEFAULT 0,
    bug_first         boolean,
    revealed_solution boolean     NOT NULL DEFAULT false,
    runs_detail       jsonb       NOT NULL DEFAULT '[]',
    created_at        timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE (job_id, sys_profile, started_at)
);

CREATE INDEX IF NOT EXISTS challenge_attempts_profile_idx
    ON web.challenge_attempts (sys_profile, started_at DESC);

-- The generator now records which module holds the planted bug and which tests
-- that bug breaks, so an upload can be scored without asking the candidate.
-- Never rendered in the exercise or the brief — scoring data only.
ALTER TABLE web.jobs_challenge ADD COLUMN IF NOT EXISTS bug_module text NOT NULL DEFAULT '';
ALTER TABLE web.jobs_challenge ADD COLUMN IF NOT EXISTS bug_tests  text[] NOT NULL DEFAULT '{}';

-- Revealing the reference solution is itself a fact about an attempt, so it
-- joins the audit log alongside the draft/save events.
ALTER TABLE web.application_events
    DROP CONSTRAINT IF EXISTS application_events_event_type_check;
ALTER TABLE web.application_events
    ADD CONSTRAINT application_events_event_type_check
    CHECK (event_type IN (
        'status_changed', 'applied', 'skipped', 'screen', 'interview',
        'rejected', 'offer', 'viewed', 'resume_drafted',
        'resume_finalized', 'resume_generated', 'resume_template_saved',
        'cover_letter_drafted', 'cover_letter_saved',
        'challenge_drafted', 'challenge_saved', 'challenge_solution_revealed'
    ));
